# Generated by Django 4.2.3 on 2023-07-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Speisekarte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gericht',
            old_name='describtion',
            new_name='description',
        ),
    ]
