# Generated by Django 4.2.3 on 2023-07-04 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Speisekarte', '0003_kategorie_gericht_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorie',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gericht',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Speisekarte.kategorie'),
        ),
    ]
