# Generated by Django 4.2.3 on 2023-07-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Speisekarte', '0004_kategorie_priority_alter_gericht_kategorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gericht',
            options={'ordering': ('name', 'description', 'preis', 'kategorie'), 'verbose_name': 'Gericht', 'verbose_name_plural': 'Gerichte'},
        ),
        migrations.AlterModelOptions(
            name='kategorie',
            options={'ordering': ('name', 'priority'), 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
    ]
